language: scala

env:
  global:
    - PUBLISH_JDK=openjdk6 # admin/build.sh only publishes when running on this jdk
# Don't commit sensitive files, instead commit a version encrypted with $SECRET,
# this environment variable is encrypted with this repo's private key and stored below:
# (See http://docs.travis-ci.com/user/environment-variables/#Secure-Variables.)
    - secure: "L51aaOUw+VZQB6XW4e3MrediaFx8hH876sSXUkEDyoYpWo+xYOBS5xj9zlTAuIDFunbsetk9CX1q22nYdfQjhlb49bxm9WyOsZp1ZmoEmWUG3NoEAZVu0dWt9Gtn1Qz3xiBiS5kzpWMEviBH/DyE1Go2BateUpzs2CfGW8eG0ss="

script:
  - admin/build.sh

scala:
  - 2.11.2
jdk:
  - openjdk6
  - openjdk7
notifications:
  email:
    - adriaan.moors@typesafe.com
